# Generated by Django 5.2.17 on 2026-08-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeorgianLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=1, unique=True)),
                (
                    "ru_translit",
                    models.CharField(
                        help_text="Как звучит буква по-русски, напр. 'дж' для ჯ",
                        max_length=4,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Название буквы", max_length=50
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("vowel", "Гласная"),
                            ("k", "К-звуки"),
                            ("t", "Т-звуки"),
                            ("p", "П/Ф-звуки"),
                            ("s", "С/Ш-звуки"),
                            ("ts", "Ц-звуки"),
                            ("ch", "Ч-звуки"),
                            ("guttural", "Гортанные"),
                            ("other", "Прочие"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Буква грузинского алфавита",
                "verbose_name_plural": "Буквы грузинского алфавита",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("georgian_text", models.CharField(max_length=100)),
                (
                    "ru_translit",
                    models.CharField(
                        help_text="Как слово читается по-русски (авто-генерируется из букв, но можно поправить)",
                        max_length=150,
                    ),
                ),
                ("translation_ru", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="learning.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
                "ordering": ["category__order", "georgian_text"],
            },
        ),
    ]
