# Generated by Django 5.2.17 on 2026-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="georgian_text",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
