# Generated by Django 5.2.17 on 2026-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_word_georgian_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('basic', 'Базовый'), ('advanced', 'Сложный')], default='basic', max_length=10),
        ),
    ]
